backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "settings"
    label: "Settings"
    files:
      - file: "site/data/settings.yml"
        label: "Global Settings"
        name: "globalSettings"
        fields:
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Website", name: "url", widget: "text"}
          - {label: "Description", name: "description", widget: "text", required: false}
          - {label: "Keywords", name: "keywords", widget: "text", required: false}
          - {label: "Open Graph Image", name: "og_image", widget: "image"}
          # - {label: "Google Tag Manager ID", name: "gtm_id", widget: "text", required: false}
  - name: "pages"
    label: "Sections"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Hero Image", name: image, widget: image}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "markdown"}]}
          - {label: "Menu Sections", name: menu, widget: list, fields: [
              {label: "Heading", name: "heading", widget: "text"},
              {label: "ID", name: "id", widget: "text", required: true},
              {label: "Text", name: "text", widget: "markdown"}]}
          - {label: "Pictures", name: "gallery", widget: "list", fields: [
              {label: "Title", name: "imgTitle", widget: "string"},
              {label: "Image", name: "imgSrc", widget: "image"}]}
          - {label: "Social Media Links", name: "socials", widget: "list", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Icon", name: "icon", widget: "string"},
              {label: "Link", name: "url", widget: "string"}]}